# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'Youtube-Sync.sln'
    publishWebProjects: false
    zipAfterPublish: false
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src\bin\Debug\netcoreapp2.2\win10-x64\publish\'
    ArtifactName: 'drop'
    publishLocation: 'Container'